### ISSUE TITLE
Swagger für Nevaris Build

### ISSUE THREAD

**Issue by louis-sicko** [NEVARISBausoftwareGmbH/http-api-client-libs#2]
Hallo,

Wir möchten auf die Nevaris-Produkte von einem Kunden via. Rest-API zugreifen.
Für Nevaris Finance haben wir die Swagger Dokumentation gefunden, jedoch für Nevaris Build haben wir bis jetzt nur dieses GitHub Repo gefunden. Gibt es für Build auch eine Dokumentation?

Vielen Dank!

**Comment by louis-sicko** [comment]
Beispiel für die Swagger Dokumentation für Finance:

https://nevfinanceapi.azurewebsites.net

**Comment by NEVARISBausoftwareGmbH** [comment]
Hallo Louis-Sicko,
können Sie mir bitte Ihre Kontaktdaten per E-Mail (bernhard.mayr@nevaris.com) zukommen lassen?
Vielen Dank
Bernhard Mayr
